import createHashMap from "./HashMap.js";
import createHashSet from "./HashSet.js";

const test = createHashMap();
test.set('apple', 'red')
test.set('banana', 'yellow')
test.set('carrot', 'orange')
test.set('dog', 'brown')
test.set('elephant', 'gray')
test.set('frog', 'green')
test.set('grape', 'purple')
test.set('hat', 'black')
test.set('ice cream', 'white')
test.set('jacket', 'blue')
test.set('kite', 'pink')
test.set('lion', 'golden')
// test.set('lion', 'black')
// test.set('kite', 'blue')
test.set('cobra', 'green')
test.set('bat', 'black')
console.log(test.remove('apple'))
test.remove('frog')
test.remove('bat')
test.clear()
console.log("--------------")
console.log(test.length())
console.log(test.buckets)

const test2 = createHashSet();
test2.set('apple')
test2.set('banana')
test2.set('carrots')
console.log(test2.get('apple'))
console.log(test2.get("balls"))
console.log(test2.has('apple'))
console.log(test2.has('balls'))
console.log(test2.remove("apple"))
console.log(test2.remove('banana'))
console.log(test2.remove('carrots'))
console.log(test2.remove("balls"))
test2.set('apple')
test2.set('banana')
test2.set('carrots')
test2.set('appl')
test2.set('banaa')
test2.set('carrts')
test2.set('aple')
test2.set('baana')
test2.set('carots')
test2.set('aple')
test2.set('baana')
test2.set('carots')
test2.set('ape')
test2.set('baaa')
test2.set('caros')
test2.set('apl')
test2.set('nvda')
test2.set('stl')
test2.remove('carrts')
test2.remove('baaa')
test2.remove('appl')
test2.remove('carrots')

console.log("----------------")
console.log(test2.length())
console.log(test2.buckets)